const {createDocument,calculateImposition,swapActivities}=window.PassportCore;
const KEY='pasaporte-andres-v3';let doc=createDocument(12),originals=JSON.stringify(doc);
const $=id=>document.getElementById(id),page=n=>doc.pages.find(p=>p.number===Number(n));
const blank=p=>['blank','blank-frame','blank-image'].includes(p.template);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function renderPage(p){const a=p.activity||{},bg=p.image?.src?`<img class="watermark" src="${p.image.src}" style="width:${p.image.scale}%;height:${p.image.scale}%;left:${50-p.image.scale/2+p.image.x}%;top:${50-p.image.scale/2+p.image.y}%;opacity:${p.image.opacity/100}">`:'';return `<article class="page ${p.number<3?'special':''} ${blank(p)?'blank-template':''}" style="border-color:${p.frameColor}" data-page="${p.number}">${p.showNumber?`<span class="number">PÁGINA ${p.number}</span>`:''}${bg}${blank(p)?'':`<h2>${esc(a.title)}</h2><p>${esc(a.description)}</p>`}</article>`}
function panel(n){return n?`<div class="panel">${renderPage(page(n))}</div>`:'<div class="panel"><article class="page blank-page"></article></div>'}
function side(label,sideName,panels){return `<section class="sheet-side"><span class="sheet-label">${label} · ${sideName}</span>${panels.map(panel).join('')}</section>`}
function renderPrint(){$('#print').innerHTML=calculateImposition(doc.pageCount).map(s=>side('PASAPORTE',s.side,s.panels)).join('')}
function load(p){$('pageSelect').value=p.number;$('template').value=p.template;$('frameColor').value=p.frameColor;$('title').value=p.activity?.title||'';$('description').value=p.activity?.description||'';$('stamp').value=p.stamp?.label||'';$('opacity').value=p.image.opacity;$('opacityOut').value=p.image.opacity+'%'}
function fill(){$('pageSelect').innerHTML=doc.pages.map(p=>`<option value="${p.number}">Página ${p.number}</option>`).join('');const x=doc.pages.filter(p=>p.number>2).map(p=>`<option value="${p.number}">${p.number}</option>`).join('');$('from').innerHTML=x;$('to').innerHTML=x;load(page($('pageSelect').value)||doc.pages[0])}
function render(){$('pageCount').value=doc.pageCount;$('logical').innerHTML=`<div class="logical-grid">${doc.pages.map(renderPage).join('')}</div>`;renderPrint();fill()}
function selected(){return page($('pageSelect').value)}function notify(s){$('match').textContent=s}
$('pageSelect').onchange=()=>load(selected());$('savePage').onclick=()=>{const p=selected();p.template=$('template').value;p.frameColor=$('frameColor').value;if(p.activity){p.activity.title=$('title').value.trim();p.activity.description=$('description').value.trim()}render();notify('Página actualizada.')};$('newDoc').onclick=()=>{const n=Number($('pageCount').value);if(Number.isInteger(n)&&n>=2&&n%2===0){doc=createDocument(n);render()}};$('save').onclick=()=>{localStorage.setItem(KEY,JSON.stringify(doc));notify('Cambios guardados.')};$('restore').onclick=()=>{const s=localStorage.getItem(KEY);if(s){doc=JSON.parse(s);render()}};$('reset').onclick=()=>{doc=JSON.parse(originals);render()};$('swap').onclick=()=>{try{swapActivities(doc,$('from').value,$('to').value);render();notify('Actividades intercambiadas.')}catch(e){notify(e.message)}};$('showNumbers').onchange=e=>{doc.pages.forEach(p=>p.showNumber=e.target.checked);render()};$('printBtn').onclick=()=>{document.querySelector('[data-tab="print"]').click();window.print()};document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.view').forEach(v=>v.classList.toggle('hidden',v.id!==b.dataset.tab))});const saved=localStorage.getItem(KEY);if(saved)try{doc=JSON.parse(saved)}catch{}doc.pages.forEach(p=>{p.image??={src:'',scale:90,x:0,y:0,opacity:23};p.stamp??={imageSrc:'Versiones/Picture1 stamp.png',label:'SELLO',subtitle:''}});render();
